runtime: nodejs16

service: api

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

includes:
  - env_variables.yaml